language: objective-c
osx_image: xcode7
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - cd CocoaHeadsNL
script:
  - xctool -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
