# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'

trigger:
- master
- feature/*

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'CocoaHeadsNL'
    sdk: '
    configuration: 'Debug'
    xcodeVersion: '11'

- task: Xcode@5
  inputs:
    actions: 'archive'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcodeproj/CocoaHeadsNL.xcworkspace'
    scheme: 'CocoaHeadsNL'
    packageApp: true
    archivePath: 'anils_archive'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iphoneos''