# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'

trigger:
- master
- feature/*

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'CocoaHeadsNL'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcodeVersion: '11'

# - task: Xcode@5
#   inputs:
#     actions: 'archive'
#     configuration: 'Debug'
#     sdk: 'iphoneos'
#     xcWorkspacePath: 'CocoaHeadsNL/CocoaHeadsNL.xcodeproj/project.xcworkspace'
#     scheme: 'CocoaHeadsNL'
#     packageApp: true
#     archivePath: 'anils_archive'
#     destinationPlatformOption: 'custom'
#     destinationPlatform: 'iphoneos'

# - task: Xcode@5
#   inputs:
#     actions: 'archive'
#     configuration: 'Release'
#     sdk: 'iphoneos'
#     xcWorkspacePath: 'CocoaHeadsNL/CocoaHeadsNL.xcodeproj/project.xcworkspace'
#     scheme: 'CocoaHeadsNL'
#     packageApp: true
#     archivePath: 'anilsarchives'
#     exportPath: 'anils_export'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'xcodebuild -sdk iphoneos -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj -configuration Release -scheme CocoaHeadsNL -derivedDataPath DerivedData -archivePath DerivedData/Archive/CocoaHeadsNL archive'