name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: ./provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj -configuration Release -scheme CocoaHeadsNL -derivedDataPath DerivedData -archivePath DerivedData/Archive/CocoaHeadsNL archive
    - name: Dump file hierarchy
      run: ls -R
    - name: Export Archive
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/CocoaHeadsNL.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
    # - name: Deploy App to Apple
      # run: xcrun altool --upload-app --type ios --file DerivedData/archive/CocoaHeadsNL.ipa --username $(appstore-connect-username) --password $(appstore-connect-password) --verbose
        